import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Todo_App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return <>
    {children}

    <section>There will be a whole new component for the todo list</section>

    <input type="text" placeholder="Add a new todo" />
    <form action="/api/todos">
      <button type="submit">Add Todo</button>
    </form>
  </>;
}
