import type { Metadata } from "next";
import { ReactNode } from "react";
import { Sidebar } from "@/components/dashboard/dashboard-index";

export const metadata: Metadata = {
  title: "Todo_App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <div className="min-h-screen grid grid-cols-[16rem_1fr] bg-background text-foreground">
      <Sidebar />
      <div className="p-6 bg-background">{children}</div>
    </div>
  );
}
