import type { Metadata } from "next";
import { ReactNode } from "react";
import { Section } from "@/components/components-index";

export const metadata: Metadata = {
  title: "Todo_App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <Section containerClassName="grid place-items-center">{children}</Section>
  );
}
